# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('TestOrderID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('PatientID', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
